variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
stages:
  - maven

maven:
  image: maven:3.6.1-jdk-8-slim
  stage: maven
  script:
    - mvn $MAVEN_CLI_OPTS compile
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  retry:
    max: 2
    when: stuck_or_timeout_failure